FROM python:3.11-slim

# Install PyTorch
RUN pip install torch -f https://download.pytorch.org/whl/cpu/torch_stable.html

# Copy your application code
WORKDIR /app
COPY . /app

# Install Python dependencies
RUN pip install -r requirements.txt

# Command to run your app
CMD ["python", "app.py"]
